# BLE Configurations
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Battery Reporting
CONFIG_ZMK_BATTERY_REPORTING=y

# PWM Backlight
CONFIG_ZMK_BACKLIGHT=y

# Poor man's LED indicator
CONFIG_INDICATOR_LED_WIDGET=y
CONFIG_INDICATOR_LED_SHOW_BLE=y

# Enable PWM LED driver for backlight
CONFIG_LED=y
CONFIG_LED_PWM=y
